name: Semantic Pull Request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  semantic:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: .github/helper/validate_pr_title.sh "$PR_TITLE"
